#!/usr/bin/env bash
# alias ls='ls --color=auto'
alias ls='exa --icons'
alias ll='ls -alhF'
alias la='ls -a'
alias l='ls -F'
alias grep='grep --color=auto'
alias k='kubectl'
alias git='LANG=en_US.UTF-8 git'
alias sudo='sudo '
alias vim='nvim'

# Extract various archives
extract() {
    if [ -f "$1" ]; then
        case $1 in
            *.tar.bz2) tar xvjf "$1" ;;
            *.tar.gz) tar xvzf "$1" ;;
            *.tar.xz) tar xvJf "$1" ;;
            *.bz2) bunzip2 "$1" ;;
            *.rar) unrar x "$1" ;;
            *.gz) gunzip "$1" ;;
            *.tar) tar xvf "$1" ;;
            *.tbz2) tar xvjf "$1" ;;
            *.tgz) tar xvzf "$1" ;;
            *.zip) unzip "$1" ;;
            *.Z) uncompress "$1" ;;
            *.7z) 7z x "$1" ;;
            *) echo "Unable to extract '$1'" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Go up directory tree X number of directories
# Source: http://orangesplotch.com/bash-going-up/
up() {
    counter="$1"

    if [[ -z ${counter} ]]; then
        counter=1
    fi

    if [[ ! ${counter} =~ ^[0-9]+$ ]]; then
        echo "Usage: up [NUMBER]"
        return 1
    fi

    nwd=$(pwd)
    until [[ ${counter} -lt 1 ]]; do
        nwd=$(dirname "${nwd}")
        ((counter -= 1))
    done
    cd "${nwd}" || return 1
}
